# Generated by Django 4.1 on 2022-08-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_customer_remove_subscribe_id_alter_subscribe_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.FileField(upload_to='customer/'),
        ),
    ]
