# Generated by Django 4.1 on 2022-08-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_customer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='feature/')),
                ('icon', models.FileField(upload_to='feature/')),
                ('icon_background', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('testimonial_description', models.TextField()),
                ('testimonial_author', models.CharField(max_length=128)),
                ('designation', models.CharField(max_length=255)),
                ('testimonial_logo', models.FileField(upload_to='feature/')),
            ],
        ),
    ]
