# Generated by Django 4.1 on 2022-09-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='videoBlog/')),
                ('title', models.CharField(max_length=255)),
                ('logo', models.FileField(upload_to='videoBlog/logo/')),
            ],
        ),
    ]
