# Generated by Django 4.1 on 2022-09-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_blog_marketingfeature_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='testimonial/logo'),
        ),
    ]
