# Generated by Django 4.1 on 2022-09-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_blog_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='background',
            field=models.CharField(default='abcd', max_length=128),
            preserve_default=False,
        ),
    ]
