# Generated by Django 4.1 on 2022-09-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_product_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='text',
            field=models.CharField(default='abcd', max_length=255),
            preserve_default=False,
        ),
    ]
